### ISSUE TITLE
docs: guide to-do list

### ISSUE THREAD

**Issue by p-nedelchev** [clouway/docs.clouway.com#82]
Lists of guides that need to be added:
General:
* [x] description of documents generated by Politis

Web:

* [x] web order-shipments flow
* [x] working with invoices - creating invoice for services, invoice notes (credit, debit)

Mobile:
 
* [ ] stock control (transfers, purchase orders)
* [ ] reports - daily report, cash report, cash register operations
* [ ] settings - printers
* [x] pricing policies
